apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: microservices-platform
  description: GCP Kubernetes microservices platform with supply chain security
  tags:
    - gcp
    - kubernetes
    - slsa
    - supply-chain-security
  links:
    - url: https://github.com/blackskyi/gcp-k8s-microservices
      title: GitHub Repository
      icon: github
    - url: https://github.com/blackskyi/gcp-k8s-microservices/security
      title: Security Center
      icon: security
spec:
  owner: platform-team
  domain: cloud-platform

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: cloud-platform
  description: Cloud platform and infrastructure
spec:
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform engineering team
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: supply-chain-security
  description: Supply chain security infrastructure and policies
  annotations:
    github.com/project-slug: blackskyi/gcp-k8s-microservices
  tags:
    - security
    - slsa
    - sigstore
    - kyverno
    - trivy
  links:
    - url: https://github.com/blackskyi/gcp-k8s-microservices/blob/main/SUPPLY-CHAIN-SECURITY.md
      title: Security Documentation
      icon: docs
    - url: https://rekor.sigstore.dev
      title: Rekor Transparency Log
      icon: dashboard
spec:
  type: infrastructure
  lifecycle: production
  owner: platform-team
  system: microservices-platform

  # Security Tools
  securityTools:
    - name: GitHub Attestations
      purpose: SLSA provenance and image signing
      version: v1

    - name: Trivy
      purpose: Container vulnerability scanning
      severity: CRITICAL,HIGH
      ignoreUnfixed: true

    - name: Kyverno
      purpose: Policy enforcement and admission control
      version: v1.11.4
      policies:
        - verify-signed-images
        - security-best-practices
        - block-latest-tag

    - name: Sigstore
      purpose: Keyless signing via GitHub OIDC
      components:
        - Rekor (transparency log)
        - Fulcio (certificate authority)

    - name: Dependabot
      purpose: Automated dependency updates
      schedule: weekly
      ecosystems:
        - npm
        - pip
        - docker
        - github-actions
        - terraform
